### ISSUE TITLE
KitchenSink asks for Kivy 2.2.0 whereas the latest release of Kivy is 2.1.0

### ISSUE THREAD

**Issue by paulvanharen** [kivymd/KitchenSink#3]
Downloaded and installed Kivy and kivyMD using pip. Downloaded KitchenSink using git.

Latest release of Kivy is 2.1.0, see [release documentation](https://github.com/kivy/kivy/releases), but KitchenSink is asking for Kivy 2.2.0.

`import kivy`
`kivy.require("2.2.0")`

**Comment by HeaTTheatR** [comment]
```
pip install https://github.com/kivy/kivy/archive/master.zip
pip install https://github.com/kivymd/KivyMD/archive/master.zip
```
