### ISSUE TITLE
The version of Kivy installed on this system is too old

### ISSUE THREAD

**Issue by masoodcmpy** [kivymd/KitchenSink#4]
Hi,  
when i run python main.py i get error: ` The version of Kivy installed on this system is too old, but the application requires 2.2.0 `  
My kivy version is 2.1.0  and my python is : 3.10.8
whene i try to install kivy v 2.2.0 by  this command:  `python -m pip install kivy==2.2.0`  i get error:  
```
ERROR: Could not find a version that satisfies the requirement kivy==2.2.0 (from versions: 1.0.1a0, 1.0.2a0, 1.0.3a0, 1.0.4b0, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.1.0, 1.1.1, 1.2.0, 1.3.0, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.11.1, 2.0.0rc1, 2.0.0rc2, 2.0.0rc3, 2.0.0rc4, 2.0.0, 2.1.0.dev0, 2.1.0rc1, 2.1.0rc2, 2.1.0rc3, 2.1.0)
ERROR: No matching distribution found for kivy==2.2.0
```

Thank You

**Comment by HeaTTheatR** [comment]
https://github.com/kivymd/KivyMD#how-to-fix-a-shader-bug-on-an-android-device

**Comment by RubenHeul** [comment]
@masoodcmpy How did you fix it?

**Comment by masoodcmpy** [comment]
@RubenHeul

[https://github.com/kivymd/KivyMD#how-to-fix-a-shader-bug-on-an-android-device](https://github.com/kivymd/KivyMD#how-to-fix-a-shader-bug-on-an-android-device)
