### ISSUE TITLE
bad screen on windows

### ISSUE THREAD

**Issue by retsyo** [kivymd/KitchenSink#9]
I run new-cloned KitchenSink on windows 10 64 bits, with
```
Kivy-Garden-0.1.5 
kivy-2.2.1 
kivy-deps.angle-0.3.3 
kivy-deps.glew-0.3.1 
kivy-deps.sdl2-0.6.0 
kivymd-1.1.1 
pypiwin32-223
```
on the main page, I use mouse wheel to scroll down, but I get this image with unneeded black block
![bug](https://github.com/kivymd/KitchenSink/assets/7960913/9c88f815-7f4c-407d-9d0e-e8126fe20099)

**Comment by HeaTTheatR** [comment]
Use KivyMD fron master branch
